name: snazzy-env
channels:
  - conda-forge
  - defaults
dependencies:
  - ipykernel=6.29.3
  - nbstripout=0.7.1
  - nd2=0.10.3
  - python=3.11
  - pandas=2.2.2
  - scipy=1.13.1
  - seaborn=0.13.2
  - ipywidgets=8.1.5
  - tifffile=2024.12.12
  - tqdm=4.66.4
  - pip=25.1.1
  - pydantic[version='<2']
  - scikit-learn=1.6.1
  - scikit-image=0.25.0
  - pip:
    - coverage==7.10.2
    - ipympl==0.9.4
    - ipython-genutils==0.2.0
    - pyqt6==6.8.0
    - pyqt6-qt6==6.8.1
    - pyqt6-sip==13.9.1
    - pyqtgraph==0.13.7   
    - pytest==8.3.5
    - pytest-qt==4.5.0
    - statannotations==0.7.1
    - sphinx-book-theme==1.1.2
    - sphinx==7.3.7
