name: pasnascope_analysis
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - aom=3.6.0
  - asttokens=2.0.5
  - attrs=23.2.0
  - blas=1.0
  - blosc=1.21.3
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2024.3.11
  - cfitsio=3.470
  - charls=2.2.0
  - comm=0.2.1
  - contourpy=1.2.0
  - cycler=0.11.0
  - cyrus-sasl=2.1.28
  - dav1d=1.2.1
  - dbus=1.13.18
  - debugpy=1.6.7
  - decorator=5.1.1
  - executing=0.8.3
  - expat=2.5.0
  - fontconfig=2.14.1
  - fonttools=4.25.0
  - freetype=2.12.1
  - giflib=5.2.1
  - glib=2.78.4
  - glib-tools=2.78.4
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - icu=73.1
  - imagecodecs=2023.1.23
  - imageio=2.33.1
  - importlib_resources=6.3.0
  - intel-openmp=2023.1.0
  - ipykernel=6.28.0
  - ipympl=0.9.3
  - ipython=8.20.0
  - ipython_genutils=0.2.0
  - ipywidgets=8.1.2
  - jedi=0.18.1
  - joblib=1.2.0
  - jpeg=9e
  - jsonschema=4.21.1
  - jsonschema-specifications=2023.12.1
  - jupyter_client=8.6.0
  - jupyter_core=5.5.0
  - jupyterlab_widgets=3.0.10
  - jxrlib=1.1
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lazy_loader=0.3
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libaec=1.0.4
  - libavif=0.11.1
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcups=2.4.2
  - libcurl=8.5.0
  - libdeflate=1.17
  - libedit=3.1.20230828
  - libev=4.33
  - libffi=3.4.4
  - libgcc-ng=13.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libglib=2.78.4
  - libgomp=13.2.0
  - libiconv=1.16
  - libllvm14=14.0.6
  - libnghttp2=1.57.0
  - libpng=1.6.39
  - libpq=12.17
  - libsodium=1.0.18
  - libssh2=1.10.0
  - libstdcxx-ng=13.2.0
  - libtiff=4.5.1
  - libuuid=1.41.5
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxkbcommon=1.0.1
  - libxml2=2.10.4
  - libzopfli=1.0.3
  - lz4-c=1.9.4
  - matplotlib=3.8.0
  - matplotlib-base=3.8.0
  - matplotlib-inline=0.1.6
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - munkres=1.1.4
  - mysql=5.7.24
  - nbformat=5.10.3
  - nbstripout=0.7.1
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - networkx=3.1
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openjpeg=2.4.0
  - openssl=3.2.1
  - packaging=23.1
  - parso=0.8.3
  - pcre2=10.42
  - pexpect=4.8.0
  - pillow=10.2.0
  - pip=23.3.1
  - pkgutil-resolve-name=1.3.10
  - platformdirs=3.10.0
  - ply=3.11
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pygments=2.15.1
  - pyparsing=3.0.9
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - python=3.11.8
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.19.1
  - python_abi=3.11
  - pyzmq=25.1.2
  - qt-main=5.15.2
  - readline=8.2
  - referencing=0.33.0
  - rpds-py=0.18.0
  - scikit-image=0.22.0
  - scikit-learn=1.2.2
  - scipy=1.11.4
  - setuptools=68.2.2
  - sip=6.7.12
  - six=1.16.0
  - snappy=1.1.10
  - sqlite=3.41.2
  - stack_data=0.2.0
  - tbb=2021.8.0
  - threadpoolctl=2.2.0
  - tifffile=2023.4.12
  - tk=8.6.12
  - tornado=6.3.3
  - traitlets=5.7.1
  - tzdata=2024a
  - wcwidth=0.2.5
  - wheel=0.41.2
  - widgetsnbextension=4.0.10
  - xz=5.4.6
  - zeromq=4.3.5
  - zfp=1.0.0
  - zipp=3.17.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - iniconfig==2.0.0
      - pluggy==1.4.0
      - pytest==8.1.1
prefix: /home/cdp58/miniconda3/envs/pasnascope_analysis
