name: pscope
channels:
  - conda-forge
  - defaults
dependencies:
  - ipykernel=6.28.0
  - ipympl=0.9.3
  - ipywidgets=8.1.2
  - matplotlib=3.8.0
  - nbformat=5.10.3
  - nbstripout=0.7.1
  - nd2=0.10.1
  - numpy=1.26.4
  - pip=23.3.1
  - python=3.11.8
  - scikit-image=0.22.0
  - scikit-learn=1.2.2
  - scipy=1.11.4
  - setuptools=68.2.2
  - tifffile=2023.4.12
  - pip:
      - pytest==8.1.1
      - sphinx-book-theme==1.1.2
      - sphinx==7.3.7