name: pscope_analysis
channels:
  - conda-forge
  - defaults
dependencies:
  - ipykernel=6.29.3
  - nbstripout=0.7.1
  - python=3.11
  - pandas=2.2.2
  - scipy=1.13.1
  - seaborn=0.13.2
  - ipywidgets=8.1.5
  - tifffile=2024.12.12
  - pip:
    - ipympl==0.9.4
    - ipython-genutils==0.2.0
    - pyqt6==6.8.0
    - pyqt6-qt6==6.8.1
    - pyqt6-sip==13.9.1
    - pyqtgraph==0.13.7   
